- Project.toml
- README.md
- readme_generator.jl
- src/ThreadsBasics.jl
- src/implementation.jl
- test/runtests.jl
This is an alternative to https://github.com/MasonProtter/ThreadsBasics.jl/pull/2
Basic idea is just that if the user doesn't want to specify the output type of `tmap`, then we just do a sequential `map` on each task, and then join those results together using  `BangBang.append!!`. 
This is type stable and inference friendly, though it does result in more allocations and is generally a bit slower.
> Add option to not provide return type to `map`/`collect`

- README.md
- src/OhMyThreads.jl
- src/implementation.jl
- test/runtests.jl
Implements https://github.com/JuliaFolds2/OhMyThreads.jl/issues/11
Like `split=:scatter`, this option is a bit scary to expose for `tmapreduce` because it also requires that the reducing op be commutative.
I almost wonder if we should do some sort of argument validation to detect if the user gave us a non-commutative reducing operator...
e.g.
```julia
julia> treduce(vcat, [:a, :b, :c, :d, :e, :f, :g])
7-element Vector{Symbol}:
:a
:b
:c
:d
:e
:f
:g
julia> treduce(vcat, [:a, :b, :c, :d, :e, :f, :g], schedule=:greedy, init=Symbol[])
7-element Vector{Symbol}:
:b
:f
:a
:g
:d
:e
:c
```
This is not a problem for `tforeach`, `tmap(f, OutputElementType, A)`, or `tmap!`, but it *is* a concern for regular `tmap`, as well as `tmapreduce`, `treducemap`, and `treduce`. 
One other potential problem is …
> Implement greedy scheduler

- src/OhMyThreads.jl
The doc string was describing `tmapreduce` instead of `treduce`. This PR corrects that.
> Correct doc string for `treduce`

- docs/make.jl
- docs/src/refs/api.md
- docs/src/translation.md
Preview: https://juliafolds2.github.io/OhMyThreads.jl/previews/PR29/translation/
Closes #24
> Base.Threads → OhMyThreads translation page for docs

- Project.toml
- docs/make.jl
- docs/src/examples/tls/Project.toml
- docs/src/examples/tls/tls.jl
- docs/src/examples/tls/tls.md
- src/OhMyThreads.jl
* added TLS.jl as a dependency
* create a (temporary) doc page with a basic example
**Preview**: https://juliafolds2.github.io/OhMyThreads.jl/previews/PR38/examples/tls/tls/
Closes #25
> TaskLocalStorage

- src/implementation.jl
<details><summary> Before </summary>
<p>
```julia
julia> tmapreduce(sin, +, 1:100; asdasb=1)
ERROR: TaskFailedException
Stacktrace:
[1] wait
@ ./task.jl:352 [inlined]
[2] fetch
@ ./task.jl:372 [inlined]
[3] fetch(t::StableTasks.StableTask{Union{}})
@ StableTasks.Internals ~/.julia/packages/StableTasks/8197D/src/internals.jl:9
[4] _mapreduce(f::typeof(fetch), op::typeof(+), ::IndexLinear, A::Vector{StableTasks.StableTask{Union{}}})
@ Base ./reduce.jl:440
[5] _mapreduce_dim(f::Function, op::Function, ::Base._InitialValue, A::Vector{StableTasks.StableTask{Union{}}}, ::Colon)
@ Base ./reducedim.jl:365
[6] mapreduce(f::Function, op::Function, A::Vector{StableTasks.StableTask{Union{}}})
@ Base ./reducedim.jl:357
[7] _tmapreduce(f::Function, op::Function, Arrs::Tuple{…}, ::Type{…}, …
```
> Reject unsupported kwargs early

- .github/workflows/changelog.yml
Can be skipped by giving a PR the "Skip-Changelog".
> Add GH action to enforce CHANGELOG.md updates for PRs

- CHANGELOG.md
- README.md
- docs/make.jl
- docs/src/examples/integration/integration.jl
- docs/src/examples/integration/integration.md
- docs/src/examples/juliaset/juliaset.jl
- docs/src/examples/juliaset/juliaset.md
- docs/src/examples/mc/mc.jl
- docs/src/examples/mc/mc.md
- docs/src/examples/tls/tls.jl
- docs/src/examples/tls/tls.md
- docs/src/examples/tomarkdown.sh
- docs/src/index.md
- docs/src/refs/api.md
- docs/src/translation.md
- src/OhMyThreads.jl
- src/implementation.jl
- src/schedulers.jl
- test/runtests.jl
This PR introduces structs for different schedulers. This enables us to have different options (fields) and default values for different schedulers (#22).
**Notes:**
* The static and dynamic schedulers have `nchunks` but the greedy scheduler has `ntasks`, because it doesn't do any chunking.
* We default to `nthreads()` tasks for static and greedy but `2*nthreads()` tasks for dynamic to have a bit of load balancing by default. (unclear if this is the best choice, see questions below)
**Questions:**
* Should the default for `DynamicScheduler` be `nchunks = 2*nthreads()` or `nchunks = nthreads()`, i.e. load balancing or not?
* Maybe we should choose the latter and have a separate `LoadBalancingScheduler` as an alias for `DynamicScheduler(nchunks=2*nthreads)`?
* Should we export all scheduler …
> Schedulers as `struct`s

- CHANGELOG.md
- docs/src/refs/api.md
- docs/src/translation.md
- src/OhMyThreads.jl
- src/implementation.jl
- src/schedulers.jl
- test/runtests.jl
> `SpawnAllScheduler`

- CHANGELOG.md
- Project.toml
- docs/src/refs/api.md
- docs/src/translation.md
- src/OhMyThreads.jl
- src/implementation.jl
- src/schedulers.jl
- test/runtests.jl
* Basic support for `ChunkSplitters.Chunk` (#47)
* Deprecates `SpawnAllScheduler` in favor of `DynamicScheduler(; nchunks=0)`. I chose a deprecation here because I don't want to tag a breaking release just for this (given that we've only introduces the scheduler a few days ago, I don't think anyone is using it).
* Adds `StaticScheduler(; nchunks=0)` which for now only works if the input collection has `<= nthreads()` elements.
Closes #47
> Basic support for `ChunkSplitters.Chunk` + `nchunks=0`

- CHANGELOG.md
- Project.toml
- docs/src/refs/api.md
- src/OhMyThreads.jl
Only merge after StableTasks.jl v0.1.5 is registered (https://github.com/JuliaRegistries/General/pull/101308)
> Bump StableTasks.jl dep to forward `@fetch` and `@fetchfrom` macros

- src/OhMyThreads.jl
- src/implementation.jl
- src/schedulers.jl
I applied ExplicitImports.jl to our package and remove some stale imports in here. 
(Also, I add type-based variants of `Schedulers.chunking_enabled` but that should be a minor thing.)
> Remove stale imports etc

- CHANGELOG.md
- docs/src/literate/tls/tls.jl
- docs/src/literate/tls/tls.md
- docs/src/refs/api.md
- src/OhMyThreads.jl
- src/implementation.jl
- src/macro_impl.jl
- src/macros.jl
- src/types.jl
- test/runtests.jl
This gives a way to make it  so that you don't have to access the `TaskLocalValue` every look iteration. Rather, you only access the `TaskLocalValue` after we `@spawn` a task, i.e. basically it should match the way that you would manually use `task_local_storage`.
For things where each iteration takes a long time, this is pretty insignificant, since accessing task local storage only takes around 10ns, but for fast functions this can be really important. 
E.g. suppose we have a thread local accumulator we use in a sum:
```julia
julia> using OhMyThreads
julia> function sum_accumulator_macro(ns)
@tasks for n ∈ ns
@set reducer = (+)
@init acc::(Base.RefValue{Int}) = Ref{Int}()
acc[] = 0
for i ∈ 1:n
acc[] += i
end
acc[]
end
end;
julia> function sum_accumulator(ns)
acc = …
```
> Add `WithTaskLocals` to make the handling of task local values more efficient.

- CHANGELOG.md
- docs/src/refs/api.md
- src/OhMyThreads.jl
- src/implementation.jl
- src/schedulers.jl
- test/runtests.jl
Closes #69
E.g
```julia
julia> tmapreduce(+, 1:12; scheduler=SerialScheduler()) do i
println(i, " → ", Threads.threadid())
i
end
1 → 1
2 → 1
3 → 1
4 → 1
5 → 1
6 → 1
7 → 1
8 → 1
9 → 1
10 → 1
11 → 1
12 → 1
78
julia> @btime tmapreduce(sin, +, 1:1000; scheduler=$(SerialScheduler()));
19.824 μs (0 allocations: 0 bytes)
julia> @btime mapreduce(sin, +, 1:1000);
19.833 μs (0 allocations: 0 bytes)
```
> Add `SerialScheduler`

- CHANGELOG.md
- src/implementation.jl
- src/macro_impl.jl
- src/schedulers.jl
- test/runtests.jl
As discussed with @MasonProtter in private, it isn't entirely obvious what `nchunks=0` means - there are different possible interpretations - which is why we no longer support it. Instead, we introduce a new keyword argument `chunking` that can be used to toggle chunking.
Corresponding part of the docstring:
```
•  chunking::Bool (default true):
• Controls whether input elements are grouped into chunks (true) or not (false).
• For chunking=false, the arguments nchunks, chunksize, and split are ignored and input elements are
regarded as "chunks" as is. Hence, there will be one parallel task spawned per input element. Note that,
depending on the input, this might spawn many(!) tasks and can be costly!
```
Example:
```julia
julia> Threads.nthreads()
6
julia> tmapreduce(+, 1:12; …
```
> Disabling Chunking: unsupport `nchunks=0` in favor of `chunking=false`

- src/implementation.jl
- test/runtests.jl
PR to change https://github.com/JuliaFolds2/OhMyThreads.jl/pull/77 since it was easier than using the code review options
This should get the tests passing on the new GreedyScheduler options, and fix an existing bug where `tmap!` would complain if you used `:batch` in it. We don't care about the re-ordering `Greedy` does for `tmap!` since the output array is already allocated and we are iterating over its indices.
> Fix for `GreedyScheduler` in tests

- CHANGELOG.md
- README.md
- docs/make.jl
- docs/src/index.md
- docs/src/literate/integration/integration.jl
- docs/src/literate/integration/integration.md
- docs/src/literate/juliaset/juliaset.jl
- docs/src/literate/juliaset/juliaset.md
- docs/src/literate/mc/mc.jl
- docs/src/literate/mc/mc.md
- docs/src/literate/tls/tls.jl
- docs/src/literate/tls/tls.md
- docs/src/translation.md
- src/functions.jl
- src/implementation.jl
- src/macro_impl.jl
- src/macros.jl
- src/schedulers.jl
- test/runtests.jl
Terminology: By "top-level" keyword arguments I refer to keyword arguments that are directly provided to the parallel function API, e.g to `tmapreduce`, `tmap`, etc. (in contrast to those provided to a `Scheduler` constructor).
**Principle:**
If `scheduler isa Symbol`, then (most) "top-level" keyword arguments are forwarded to the constructor of the `Scheduler` that corresponds to the symbol (if any). If `scheduler isa Scheduler`, to avoid ambiguity, we error if a scheduler option is provided as a "top-level" keyword argument.
**Examples** (see docstrings and `runtests.jl` for more):
```julia
julia> tmapreduce(sin, +, 1:100; scheduler=:static)
-0.12717101366042027
julia> tmapreduce(sin, +, 1:100; ntasks=2)
-0.12717101366041983
julia> tmapreduce(sin, +, 1:100; chunksize=10, …
```
> Full `scheduler::Symbol` support + Keyword argument forwarding

- CHANGELOG.md
- src/implementation.jl
- test/runtests.jl
Closes #86.
See also the cousin issue #87.
> Handle empty collections with `tmapreduce` and `tforeach`

- CHANGELOG.md
- src/implementation.jl
- src/schedulers.jl
- test/runtests.jl
Quick and dirty attempt at #66
(only very technically breaking because of the new type parameter)
> Chunking for `GreedyScheduler`

- CHANGELOG.md
- docs/src/refs/api.md
- src/OhMyThreads.jl
- src/macro_impl.jl
- src/macros.jl
- src/tools.jl
- test/runtests.jl
Addresses https://github.com/JuliaFolds2/OhMyThreads.jl/issues/73
(We don't implement implicit barriers at the end here, or options to turn those on or off. This should go into a new PR targeting #74)
> Add special region support to `@tasks`

- CHANGELOG.md
- Project.toml
While https://github.com/JuliaFolds2/Transducers.jl/issues/31 and https://github.com/JuliaML/MLUtils.jl/issues/175 are sorted out, this PR relaxes BangBang compact to v0.3 so that OhMyThreads becomes compatible with many packages in the ML ecosystem.
I tested locally on BangBang v0.3.40 and all tests pass.
> relax BangBang compat

- CHANGELOG.md
- src/implementation.jl
- test/runtests.jl
Extension of #88.
Closes #87.
With this PR, we now explicitly fall back to the serial `Base` functions if the input `isempty`.
Shouldn't be breaking because we pretty much always error'ed before.
> Handle empty input

- CHANGELOG.md
- src/implementation.jl
- test/runtests.jl
With this PR:
```julia
julia> @tasks for (c,v) in enumerate(chunks(rand(10); n=2))
@set chunking=false
@show c
end
c = 2
c = 1
julia> @tasks for (c,v) in enumerate(chunks(rand(10); n=2))
@set chunking=false
@set reducer=+
c
end
3
julia> @tasks for (c,v) in enumerate(chunks(rand(10); n=2))
@set chunking=false
@set collect=true
c
end
2-element Vector{Int64}:
1
2
```
Before this PR:
```julia
julia> @tasks for (c,v) in enumerate(chunks(rand(10); n=2))
@set chunking=false
@show c
end
ERROR: MethodError: no method matching keys(::ChunkSplitters.Enumerate{ChunkSplitters.Chunk{…}})
Closest candidates are:
keys(::Pkg.Registry.RegistryInstance)
@ Pkg ~/.julia/juliaup/julia-1.10.5+0.aarch64.apple.darwin14/share/julia/stdlib/v1.10/Pkg/src/Registry/registry_instance.jl:447
keys(::LibGit2.GitTree)
@ …
```
> Support for `enumerate(chunks(...))`

- src/macros.jl
This patch adds a clarification about the scope of the right hand sides of `@set` and `@local` right hand sides.
I had some code similar to
```julia
function f()
x = foo()
@tasks for i in 1:3
@local y = bar(x)
local x = baz()
end
end
```
which looks like it wouldn't work because `x` in `bar(x)` would normally throw an `UndefVarError`.
> Clarify the scope of `@set` and `@local`

- .github/workflows/downgrade_CI.yml
- CHANGELOG.md
- Project.toml
- docs/make.jl
- docs/src/literate/boxing/Project.toml
- docs/src/literate/boxing/boxing.jl
- docs/src/literate/boxing/boxing.md
- docs/src/refs/api.md
- src/OhMyThreads.jl
- src/implementation.jl
- src/macro_impl.jl
- src/macros.jl
- test/Aqua.jl
- test/runtests.jl
Closes #132, Closes #133
Before:
```julia
julia> let
v = tmap(1:10) do i
A = i
sleep(rand())
A
end
A = 1 # oops, now everything is a race condition!
v
end
10-element Vector{Int64}:
9
2
2
4
2
4
9
2
9
2
```
This PR:
```julia
julia> let
v = tmap(1:10) do i
A = i
sleep(rand())
A
end
A = 1 # oops, now everything is a race condition!
v
end
ERROR: Attempted to capture and modify outer local variable(s) A, which would be not only slow, but could also cause a race condition. Consider marking these variables as local inside their respective closure, or redesigning your code to avoid the race condition.
If these variables are inside a @one_by_one or @only_one block, consider using a mutable Ref instead of re-binding the variable.
This error can be bypassed with the @allow_boxed_captures macro. …
```
> Detect and throw an error when multithreading with `Box`ed variables

- .github/workflows/ci.yml
- test/runtests.jl
2 fixes:
- x64 macOS is only available on `macos-13` so change to that. I also re-add aarch64 tests because that is the more common configuration so continue testing that.
- `env` must be set per-step. I assume the step that needs to be run with multiple threads is `julia-runtests` so I changed it. I can undo if I was wrong.
> Various CI fixes

- CHANGELOG.md
- Project.toml
- src/implementation.jl
- src/schedulers.jl
- test/runtests.jl
Closes #114 and closes #72
This PR does two things:
1. It makes it so that reductions over a single chunk / (or single element in the case of no-chunking) will not hit the multithreaded path, and will instead just call `Base.mapreduce`
2. It adds a `minsize` keyword argument for schedulers so that users can say "I don't want any chunks smaller than `N` elements.
Together, this means that you can do stuff like
```julia
julia> @btime tmapreduce(sin, +, 1:10; minsize=100)
75.105 ns (3 allocations: 96 bytes)
1.4111883712180104
```
and only get a minor amount of overhead versus regular `mapreduce`.
> Support `minsize` setting; don't spawn tasks when only 1 chunk
